BEGIN;
---------------------------------------------
-- TABLE ROLES
---------------------------------------------
CREATE TABLE IF NOT EXISTS public.kruger_role (
    id_role bigint NOT NULL,
    role_description character varying(255),
    role_name character varying(255),
    PRIMARY KEY ("id_role")
);

---------------------------------------------
-- TABLE EMPLOYEE
---------------------------------------------
CREATE TABLE IF NOT EXISTS public.kruger_user (
    user_id bigint NOT NULL,
    user_password character varying(250),
    user_username character varying(100),
    user_role bigint,
    PRIMARY KEY ("user_id")
);

---------------------------------------------
-- TABLE EMPLOYEE
---------------------------------------------
CREATE TABLE IF NOT EXISTS public.kruger_employee (
    employee_id bigint NOT NULL,
    employee_address character varying(250) NOT NULL,
    employee_date_birthday date,
    employee_dni character varying(10) NOT NULL,
    employee_email character varying(100) NOT NULL,
    employee_last_name character varying(100) NOT NULL,
    employee_mobile character varying(10),
    employee_name character varying(100) NOT NULL,
    employee_status_vaccine character varying(15),
    employee_user bigint,
    PRIMARY KEY ("employee_id")
);

---------------------------------------------
-- TABLE EMPLOYEE
---------------------------------------------
CREATE TABLE IF NOT EXISTS public.kruger_vaccine (
    vaccine_id bigint NOT NULL,
    vaccine_date date NOT NULL,
    vaccine_number integer NOT NULL,
    vaccine_type character varying(100) NOT NULL,
    vaccine_employee bigint,
    PRIMARY KEY ("vaccine_id")
);

ALTER TABLE public.kruger_employee ALTER COLUMN employee_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kruger_employee_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.kruger_role ALTER COLUMN id_role ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kruger_role_id_role_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.kruger_user ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kruger_user_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.kruger_vaccine ALTER COLUMN vaccine_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kruger_vaccine_vaccine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


---------------------------------------------
-- CONSTRAINT DNI_UNIQUE
---------------------------------------------
ALTER TABLE ONLY public.kruger_employee
    ADD CONSTRAINT EMPLOYEE_DNI_UNIQUE UNIQUE (employee_dni);

---------------------------------------------
-- CONSTRAINT FK_USER_ROLE
---------------------------------------------
ALTER TABLE ONLY public.kruger_user
    ADD CONSTRAINT USER_ROLE_FK FOREIGN KEY (user_role) REFERENCES public.kruger_role(id_role);

---------------------------------------------
-- CONSTRAINT FK_EMPLOYEE_USER
---------------------------------------------
ALTER TABLE ONLY public.kruger_employee
    ADD CONSTRAINT EMPLOYEE_USER_FK FOREIGN KEY (employee_user) REFERENCES public.kruger_user(user_id);

---------------------------------------------
-- CONSTRAINT FK_VACCINE_EMPLOYEE
---------------------------------------------
ALTER TABLE ONLY public.kruger_vaccine
    ADD CONSTRAINT VACCINE_EMPLOYEE_FK FOREIGN KEY (vaccine_employee) REFERENCES public.kruger_employee(employee_id);

INSERT INTO public.kruger_role(id_role, role_description, role_name)VALUES(1, 'Role for the admin users.', 'ADMIN');
INSERT INTO public.kruger_role(id_role, role_description, role_name)VALUES(2, 'Role for the employee users.', 'USER');

INSERT INTO public.kruger_user(user_id, user_password, user_username, user_role)VALUES(1,'$2a$12$KMV4MsjLNqwjH0tOzgIVNOx3RJ2fv4xDiWsRDLA8b3E3v368ZoibW', 'aBermeo', 1);

END;